spring.config.import=optional:classpath:application-test.properties
spring.jpa.defer-datasource-initialization=true

# JWT Token Configuration
api.security.token.secret=a2a6d8a8fabe3a5f3a3a7f9b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b
api.security.token.expiration-minutes=60
