# Ativado quando o perfil "postgres" estiver ativo
spring.config.activate.on-profile=postgres

# Datasource Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/daily
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Executa data.sql para semear roles
spring.sql.init.mode=always

# Desabilita console H2 neste perfil
spring.h2.console.enabled=false