# Ativado apenas quando o perfil "test" estiver ativo
spring.config.activate.on-profile=test

# Datasource H2 em memória para testes
spring.datasource.url=jdbc:h2:mem:daily_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate para testes
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT para testes
api.security.token.secret=changeit_changeit_changeit_changeit_changeit_changeit
api.security.token.expiration-minutes=60
logging.level.org.springframework.security=DEBUG
logging.level.com.vilardev.Daily=DEBUG